### ISSUE TITLE
*.grid and *.egrid data formats. what is the difference?

### ISSUE THREAD

**Issue by artemgubarev** [equinor/ecl-data-io#36]
what is the difference, *.grid and *.egrid eclipse data formats? If keyword "COORDS" in *.grid needed to store data the (x,y) coordinates of the top and bottom of the pillars constituting the grid, then why does it store 7 values ​​which is not a multiple of 2.

**Comment by eivindjahren** [comment]
There is some information about this in the eclipse user manual. I know xtgeo had support for the grid format at some point. Perhaps @jcrivenaes have any insights?

**Comment by eivindjahren** [comment]
I am closing this as there is documentation for the difference in the ecl manual under file formats. The `ecl_data_io` format can read both kinds of files, but its up for the user of `ecl_data_io` to interpret its contents.
